[package]
name = "dropcolumns"
version = "0.0.0"
authors = ["Ryan Wick <rrwick@gmail.com>"]
edition = "2018"
description = "a tool for dropping columns in a FASTA-format whole-genome pseudo-alignment"
rust-version = "1.66"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = { version = "4", features = ["derive", "cargo", "wrap_help"] }
colored = "2.0"
flate2 = "1.0"
lazy_static = "1.4.0"
num-format = "0.4"
regex = "1"
term_size = "0.3"
textwrap = "0.14"
seq_io = "0.3.1"
